apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service-luisk
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: ClusterIP
