# Default values for firstHelm.
# Para definir lso valores que se utilizarán en el despliegue
replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: stable

service:
  type: ClusterIP
  port: 80

